name: hello-world
region: nyc

services:
  - name: backend
    github:
      repo: ncprac/main_day
      branch: master
      deploy_on_push: true
    source_dir: /backend
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /api

  - name: frontend
    github:
      repo: ncprac/main_day
      branch: master
      deploy_on_push: true
    source_dir: /frontend
    http_port: 80
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /
